apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a-app
  template:
    metadata:
      labels:
        app: service-a-app
    spec:
      containers:
      - name: service-a
        image: nghialoe/service-a:latest
        ports:
        - containerPort: 8080
      #   volumeMounts:
      #   - name: config-volume
      #     mountPath: /app/config/appsettings.json
      #     subPath: appsettings.json
      # volumes:
      # - name: config-volume
      #   configMap:
      #     name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: service-a-lb
spec:
  selector:
    app: service-a-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer